name: starter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # GetX
  get: ^4.6.5
  get_storage: ^2.0.3

  # Network
  dio: ^4.0.6

  # UI
  shimmer: ^2.0.0

  # Firebase
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7

  # Information
  package_info_plus: ^1.4.3

  #Utilities
  url_launcher: ^6.1.5
  http: ^0.13.5
  convert: ^3.1.1
  get_cli: ^0.2.30
  intl: ^0.18.0
  timeago: ^3.2.2
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  data_connection_checker: ^0.3.4
  badges: ^2.0.3
  animated_splash_screen: ^1.3.0
  dropdown_button2: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: helveticaneue
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_light_italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_medium_italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_semi_bold_italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_bold_italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/poppins_bold_italic.ttf
          weight: 800
          style: italic
